{% set name = "cfenv" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cfenv-{{ version }}.tar.gz
  sha256: c7a91a4c82431acfc35db664c194d5e6cc7f4df3dcb692d0f836a6ceb0156167

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - furl >=0.4.8

test:
  imports:
    - cfenv
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jmcarp/py-cfenv
  summary: Python wrapper for Cloud Foundry environments
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - sumanth-manchala
